
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # ----------------------------------------------------------------------------
  #  Repository Info Use Case
  # ----------------------------------------------------------------------------

  App\Package\Application\GetRepositoryInfo\:
    resource: '%kernel.project_dir%/app/Package/Application/GetRepositoryInfo'
