
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Package
  App\Package\Application\Package\PackageFinder: ~
  App\Package\Application\Package\PackageListFinder: ~

  # Common (all metadata)
  App\Package\Application\Repository\RepositoryInfoProvider: ~
