
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Packagist\Domain\Name\NameParser: ~

  App\Packagist\Domain\Name\NameValidator:
    public: true
    arguments:
      $validator: '@Symfony\Component\Validator\Validator\ValidatorInterface'

