
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # ----------------------------------------------------------------------------
  #  Package Updates Use Case
  # ----------------------------------------------------------------------------

  App\Statistic\Application\Updates\:
    resource: '%kernel.project_dir%/app/Statistic/Application/Updates'
