
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Package\Domain\PackageRepositoryInterface:
    alias: App\Package\Infrastructure\Persistence\Repository\DatabasePackageRepository
