
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Package\Domain\Credentials\CredentialsParser: ~

  App\Package\Domain\Credentials\CredentialsValidator:
    public: true
    arguments:
      $validator: '@Symfony\Component\Validator\Validator\ValidatorInterface'

