# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  http_cache: true
  #csrf_protection: true

  # Note that the session will be started ONLY if you read or write from it.
  session: false

  secrets:
    vault_directory: '%kernel.project_dir%/config/secrets/%kernel.environment%'
    local_dotenv_file: '%kernel.project_dir%/.env'
    # decryption_env_var: 'base64:default::SYMFONY_DECRYPTION_SECRET'

  #esi: true
  #fragments: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
