
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Account\Domain\AccountRepositoryInterface:
    alias: App\Account\Infrastructure\Persistence\Repository\DatabaseAccountRepository
