
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # ----------------------------------------------------------------------------
  #  Collect Statistic Use Case
  # ----------------------------------------------------------------------------

  App\Packagist\Application\CollectStatistic\:
    resource: '%kernel.project_dir%/app/Packagist/Application/CollectStatistic'
