
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # ----------------------------------------------------------------------------
  #  Package List Use Case
  # ----------------------------------------------------------------------------

  App\Packagist\Application\GetPackageList\:
    resource: '%kernel.project_dir%/app/Packagist/Application/GetPackageList'
