
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # ----------------------------------------------------------------------------
  #  Package Info Use Case
  # ----------------------------------------------------------------------------

  App\Packagist\Application\GetPackageInfo\:
    resource: '%kernel.project_dir%/app/Packagist/Application/GetPackageInfo'
