
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Package\Presentation\Response\Transformer\:
    resource: '%kernel.project_dir%/app/Package/Presentation/Response/Transformer/'
