
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Account\Application\Auth\AuthenticationProcess: ~
  App\Account\Application\Auth\RegistrationProcess: ~

  App\Account\Application\Integration\IntegrationRedirectGenerator: ~
  App\Account\Application\Integration\IntegrationAccountFetcher: ~
