<?php

declare(strict_types=1);

namespace App\Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * @api
 * @internal this is an internal library class, please do not use it in your code.
 * @psalm-internal App\Database\Migrations
 */
final class Version20240902212847 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add package downloads statistic table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE statistic_package_downloads (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                ip VARCHAR(255) NOT NULL,
                name VARCHAR(255) NOT NULL,
                vendor VARCHAR(255) DEFAULT NULL,
                version VARCHAR(255) NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            DROP TABLE statistic_package_downloads
            SQL);
    }
}
