accounts:
  resource:
    path: ../app/Account/Presentation/Controller/
    namespace: App\Account\Presentation\Controller
  type: attribute
  defaults:
    _api: v1

packages:
  resource:
    path: ../app/Package/Presentation/Controller/
    namespace: App\Package\Presentation\Controller
  type: attribute
  requirements:
    vendor: '[a-z0-9]([_.-]?[a-z0-9]+)*'
    name: '[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*'
    package: '[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*'
  defaults:
    _api: packagist
