
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Packagist\Presentation\Response\Transformer\:
    resource: '%kernel.project_dir%/app/Packagist/Presentation/Response/Transformer/'
